import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

import HomepagesLayout from "@/layouts/HomepagesLayout"

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <HomepagesLayout>
                    {children}
                </HomepagesLayout>
            </body>
        </html>
    )
}
